from implement import Trie
import re, json

para = """Before AI, my job was: think about a problem, write code, test it, ship it. I was the creator. The maker. That's what drew most of us to engineering in the first place - the act of building.

After AI, my job increasingly became: prompt, wait, read output, evaluate output, decide if output is correct, decide if output is safe, decide if output matches the architecture, fix the parts that don't, re-prompt, repeat. I became a reviewer. A judge. A quality inspector on an assembly line that never stops.

This is a fundamentally different kind of work. Creating is energizing. Reviewing is draining. There's research on this - the psychological difference between generative tasks and evaluative tasks. Generative work gives you flow states. Evaluative work gives you decision fatigue.

I noticed it first during a week where I was using AI heavily for a new microservice. By Wednesday, I couldn't make simple decisions anymore. What should this function be named? I didn't care. Where should this config live? I didn't care. My brain was full. Not from writing code - from judging code. Hundreds of small judgments, all day, every day.

The cruel irony is that AI-generated code requires more careful review than human-written code. When a colleague writes code, I know their patterns, their strengths, their blind spots. I can skim the parts I trust and focus on the parts I don't. With AI, every line is suspect. The code looks confident. It compiles. It might even pass tests. But it could be subtly wrong in ways that only surface in production, under load, at 3am.

So you read every line. And reading code you didn't write, that was generated by a system that doesn't understand your codebase's history or your team's conventions, is exhausting work.

This is also why I think agent security and authorization matter so much. If we can't review everything AI produces - and we can't, not at scale - then we need systems that constrain what agents can do in the first place. Least-privilege access, scoped tokens, audit trails. The less you have to worry about "did the AI do something dangerous," the more cognitive budget you have for the work that actually matters. This isn't just a security problem. It's a human sustainability problem.
"""

def clean_para(paragraph):
    paragraph = re.sub("\n", "", paragraph)
    paragraph = re.sub(",", "", paragraph)
    paragraph = re.sub("\.", "", paragraph)
    paragraph = re.sub(":", " ", paragraph)
    paragraph = re.sub("-", " ", paragraph)
    paragraph = re.sub("    ", " ", paragraph)
    paragraph = re.sub("   ", " ", paragraph)
    paragraph = re.sub("  ", " ", paragraph)
    paragraph = re.sub("\'s", "", paragraph)
    paragraph = paragraph.lower()
    return paragraph.split(" ")

para = clean_para(para)

trie = Trie()

for i in para:
    trie.insert(i)

# result = json.dumps(trie.draw())

test_cases = ['cruel', 'manager', 'the', 'that', 'a', 'ai', 'chat', 'work', 'done', 'useless', 'week', 'architecture']
result = []
for test in test_cases:
    result.append(trie.search(test))
print(result)